name: "Setup"
description: Sets up PNPM and Node.js
runs:
  using: "composite"
  steps:
    - name: Install PNPM
      uses: pnpm/action-setup@v6
    - name: Set up Node.js with PNPM cache
      uses: actions/setup-node@v6
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: "pnpm"
        cache-dependency-path: pnpm-lock.yaml
