name: "Publish"
description: Publishes the package
inputs:
  package:
    description: "The package publish"
    required: true
  version:
    description: "The version to publish"
    required: true
  prerelease_tag:
    description:
      "The prerelease tag of the package (if any). If not provided, the package
      will be published as 'latest'."
    required: false
runs:
  using: "composite"
  steps:
    - name: Version
      shell: bash
      run: |
        pnpm --filter ${{ inputs.package }} exec pnpm version ${{ inputs.version }} --no-git-tag-version
    - name: Publish
      shell: bash
      run: |
        pnpm --filter ${{ inputs.package }} publish --access=public --no-git-checks --tag ${{ inputs.prerelease_tag || 'latest' }}
