/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'api-keys': ApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    users: User;
    'api-keys': ApiKey;
    'locale-configs': LocaleConfig;
    banners: Banner;
    pages: Page;
    redirects: Redirect;
    brands: Brand;
    'payload-kv': PayloadKv;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'api-keys': ApiKeysSelect<false> | ApiKeysSelect<true>;
    'locale-configs': LocaleConfigsSelect<false> | LocaleConfigsSelect<true>;
    banners: BannersSelect<false> | BannersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | (
        | 'en'
        | 'en-US'
        | 'en-GB'
        | 'en-CA'
        | 'en-AU'
        | 'zh'
        | 'zh-CN'
        | 'zh-TW'
        | 'zh-HK'
        | 'es'
        | 'es-ES'
        | 'es-MX'
        | 'es-AR'
        | 'es-CO'
        | 'es-CL'
        | 'ar'
        | 'ar-SA'
        | 'ar-EG'
        | 'ar-AE'
        | 'pt'
        | 'pt-BR'
        | 'pt-PT'
        | 'fr'
        | 'fr-FR'
        | 'fr-CA'
        | 'de'
        | 'de-DE'
        | 'ja'
        | 'ja-JP'
        | 'ru'
        | 'ru-RU'
        | 'hi'
        | 'hi-IN'
        | 'it'
        | 'it-IT'
        | 'ko'
        | 'ko-KR'
        | 'tr'
        | 'tr-TR'
        | 'pl'
        | 'pl-PL'
        | 'nl'
        | 'nl-NL'
        | 'sv'
        | 'sv-SE'
        | 'fi'
        | 'fi-FI'
        | 'no'
        | 'no-NO'
        | 'da'
        | 'da-DK'
        | 'id'
        | 'id-ID'
        | 'ms'
        | 'ms-MY'
        | 'th'
        | 'th-TH'
        | 'vi'
        | 'vi-VN'
        | 'he'
        | 'he-IL'
        | 'fa'
        | 'fa-IR'
        | 'uk'
        | 'uk-UA'
        | 'cs'
        | 'cs-CZ'
        | 'sk'
        | 'sk-SK'
        | 'ro'
        | 'ro-RO'
        | 'hu'
        | 'hu-HU'
        | 'el'
        | 'el-GR'
        | 'bn'
        | 'bn-BD'
        | 'bn-IN'
        | 'ta'
        | 'ta-IN'
        | 'te'
        | 'te-IN'
        | 'ml'
        | 'ml-IN'
        | 'mr'
        | 'mr-IN'
        | 'pa'
        | 'pa-IN'
        | 'gu'
        | 'gu-IN'
        | 'ur'
        | 'ur-PK'
        | 'sw'
        | 'sw-KE'
        | 'af'
        | 'af-ZA'
        | 'am'
        | 'am-ET'
        | 'et'
        | 'et-EE'
        | 'lv'
        | 'lv-LV'
        | 'lt'
        | 'lt-LT'
        | 'sl'
        | 'sl-SI'
        | 'sr'
        | 'sr-RS'
        | 'hr'
        | 'hr-HR'
        | 'bg'
        | 'bg-BG'
        | 'ka'
        | 'ka-GE'
        | 'az'
        | 'az-AZ'
        | 'hy'
        | 'hy-AM'
        | 'ne'
        | 'ne-NP'
        | 'si'
        | 'si-LK'
        | 'my'
        | 'my-MM'
        | 'km'
        | 'km-KH'
        | 'lo'
        | 'lo-LA'
        | 'mn'
        | 'mn-MN'
        | 'kk'
        | 'kk-KZ'
        | 'uz'
        | 'uz-UZ'
        | 'ps'
        | 'ps-AF'
        | 'es-419'
        | 'zh-Hans'
        | 'zh-Hant'
        | 'nb'
      )
    | (
        | 'en'
        | 'en-US'
        | 'en-GB'
        | 'en-CA'
        | 'en-AU'
        | 'zh'
        | 'zh-CN'
        | 'zh-TW'
        | 'zh-HK'
        | 'es'
        | 'es-ES'
        | 'es-MX'
        | 'es-AR'
        | 'es-CO'
        | 'es-CL'
        | 'ar'
        | 'ar-SA'
        | 'ar-EG'
        | 'ar-AE'
        | 'pt'
        | 'pt-BR'
        | 'pt-PT'
        | 'fr'
        | 'fr-FR'
        | 'fr-CA'
        | 'de'
        | 'de-DE'
        | 'ja'
        | 'ja-JP'
        | 'ru'
        | 'ru-RU'
        | 'hi'
        | 'hi-IN'
        | 'it'
        | 'it-IT'
        | 'ko'
        | 'ko-KR'
        | 'tr'
        | 'tr-TR'
        | 'pl'
        | 'pl-PL'
        | 'nl'
        | 'nl-NL'
        | 'sv'
        | 'sv-SE'
        | 'fi'
        | 'fi-FI'
        | 'no'
        | 'no-NO'
        | 'da'
        | 'da-DK'
        | 'id'
        | 'id-ID'
        | 'ms'
        | 'ms-MY'
        | 'th'
        | 'th-TH'
        | 'vi'
        | 'vi-VN'
        | 'he'
        | 'he-IL'
        | 'fa'
        | 'fa-IR'
        | 'uk'
        | 'uk-UA'
        | 'cs'
        | 'cs-CZ'
        | 'sk'
        | 'sk-SK'
        | 'ro'
        | 'ro-RO'
        | 'hu'
        | 'hu-HU'
        | 'el'
        | 'el-GR'
        | 'bn'
        | 'bn-BD'
        | 'bn-IN'
        | 'ta'
        | 'ta-IN'
        | 'te'
        | 'te-IN'
        | 'ml'
        | 'ml-IN'
        | 'mr'
        | 'mr-IN'
        | 'pa'
        | 'pa-IN'
        | 'gu'
        | 'gu-IN'
        | 'ur'
        | 'ur-PK'
        | 'sw'
        | 'sw-KE'
        | 'af'
        | 'af-ZA'
        | 'am'
        | 'am-ET'
        | 'et'
        | 'et-EE'
        | 'lv'
        | 'lv-LV'
        | 'lt'
        | 'lt-LT'
        | 'sl'
        | 'sl-SI'
        | 'sr'
        | 'sr-RS'
        | 'hr'
        | 'hr-HR'
        | 'bg'
        | 'bg-BG'
        | 'ka'
        | 'ka-GE'
        | 'az'
        | 'az-AZ'
        | 'hy'
        | 'hy-AM'
        | 'ne'
        | 'ne-NP'
        | 'si'
        | 'si-LK'
        | 'my'
        | 'my-MM'
        | 'km'
        | 'km-KH'
        | 'lo'
        | 'lo-LA'
        | 'mn'
        | 'mn-MN'
        | 'kk'
        | 'kk-KZ'
        | 'uz'
        | 'uz-UZ'
        | 'ps'
        | 'ps-AF'
        | 'es-419'
        | 'zh-Hans'
        | 'zh-Hant'
        | 'nb'
      )[];
  globals: {
    settings: Settings;
    common: Common;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    common: CommonSelect<false> | CommonSelect<true>;
  };
  locale:
    | 'en'
    | 'en-US'
    | 'en-GB'
    | 'en-CA'
    | 'en-AU'
    | 'zh'
    | 'zh-CN'
    | 'zh-TW'
    | 'zh-HK'
    | 'es'
    | 'es-ES'
    | 'es-MX'
    | 'es-AR'
    | 'es-CO'
    | 'es-CL'
    | 'ar'
    | 'ar-SA'
    | 'ar-EG'
    | 'ar-AE'
    | 'pt'
    | 'pt-BR'
    | 'pt-PT'
    | 'fr'
    | 'fr-FR'
    | 'fr-CA'
    | 'de'
    | 'de-DE'
    | 'ja'
    | 'ja-JP'
    | 'ru'
    | 'ru-RU'
    | 'hi'
    | 'hi-IN'
    | 'it'
    | 'it-IT'
    | 'ko'
    | 'ko-KR'
    | 'tr'
    | 'tr-TR'
    | 'pl'
    | 'pl-PL'
    | 'nl'
    | 'nl-NL'
    | 'sv'
    | 'sv-SE'
    | 'fi'
    | 'fi-FI'
    | 'no'
    | 'no-NO'
    | 'da'
    | 'da-DK'
    | 'id'
    | 'id-ID'
    | 'ms'
    | 'ms-MY'
    | 'th'
    | 'th-TH'
    | 'vi'
    | 'vi-VN'
    | 'he'
    | 'he-IL'
    | 'fa'
    | 'fa-IR'
    | 'uk'
    | 'uk-UA'
    | 'cs'
    | 'cs-CZ'
    | 'sk'
    | 'sk-SK'
    | 'ro'
    | 'ro-RO'
    | 'hu'
    | 'hu-HU'
    | 'el'
    | 'el-GR'
    | 'bn'
    | 'bn-BD'
    | 'bn-IN'
    | 'ta'
    | 'ta-IN'
    | 'te'
    | 'te-IN'
    | 'ml'
    | 'ml-IN'
    | 'mr'
    | 'mr-IN'
    | 'pa'
    | 'pa-IN'
    | 'gu'
    | 'gu-IN'
    | 'ur'
    | 'ur-PK'
    | 'sw'
    | 'sw-KE'
    | 'af'
    | 'af-ZA'
    | 'am'
    | 'am-ET'
    | 'et'
    | 'et-EE'
    | 'lv'
    | 'lv-LV'
    | 'lt'
    | 'lt-LT'
    | 'sl'
    | 'sl-SI'
    | 'sr'
    | 'sr-RS'
    | 'hr'
    | 'hr-HR'
    | 'bg'
    | 'bg-BG'
    | 'ka'
    | 'ka-GE'
    | 'az'
    | 'az-AZ'
    | 'hy'
    | 'hy-AM'
    | 'ne'
    | 'ne-NP'
    | 'si'
    | 'si-LK'
    | 'my'
    | 'my-MM'
    | 'km'
    | 'km-KH'
    | 'lo'
    | 'lo-LA'
    | 'mn'
    | 'mn-MN'
    | 'kk'
    | 'kk-KZ'
    | 'uz'
    | 'uz-UZ'
    | 'ps'
    | 'ps-AF'
    | 'es-419'
    | 'zh-Hans'
    | 'zh-Hant'
    | 'nb';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | ApiKey;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface ApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  comment?: string | null;
  alt?: string | null;
  folder?: (string | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: string;
  name: string;
  folder?: (string | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: string | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: string | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  role: 'editor' | 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys".
 */
export interface ApiKey {
  id: string;
  role: 'cicd' | 'frontend' | 'e2e-tests';
  remark?: string | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locale-configs".
 */
export interface LocaleConfig {
  id: string;
  locale:
    | 'af'
    | 'af-ZA'
    | 'am'
    | 'am-ET'
    | 'ar'
    | 'ar-AE'
    | 'ar-EG'
    | 'ar-SA'
    | 'az'
    | 'az-AZ'
    | 'bg'
    | 'bg-BG'
    | 'bn'
    | 'bn-BD'
    | 'bn-IN'
    | 'cs'
    | 'cs-CZ'
    | 'da'
    | 'da-DK'
    | 'de'
    | 'de-DE'
    | 'el'
    | 'el-GR'
    | 'en'
    | 'en-AU'
    | 'en-CA'
    | 'en-GB'
    | 'en-US'
    | 'es'
    | 'es-419'
    | 'es-AR'
    | 'es-CL'
    | 'es-CO'
    | 'es-ES'
    | 'es-MX'
    | 'et'
    | 'et-EE'
    | 'fa'
    | 'fa-IR'
    | 'fi'
    | 'fi-FI'
    | 'fr'
    | 'fr-CA'
    | 'fr-FR'
    | 'gu'
    | 'gu-IN'
    | 'he'
    | 'he-IL'
    | 'hi'
    | 'hi-IN'
    | 'hr'
    | 'hr-HR'
    | 'hu'
    | 'hu-HU'
    | 'hy'
    | 'hy-AM'
    | 'id'
    | 'id-ID'
    | 'it'
    | 'it-IT'
    | 'ja'
    | 'ja-JP'
    | 'ka'
    | 'ka-GE'
    | 'kk'
    | 'kk-KZ'
    | 'km'
    | 'km-KH'
    | 'ko'
    | 'ko-KR'
    | 'lo'
    | 'lo-LA'
    | 'lt'
    | 'lt-LT'
    | 'lv'
    | 'lv-LV'
    | 'ml'
    | 'ml-IN'
    | 'mn'
    | 'mn-MN'
    | 'mr'
    | 'mr-IN'
    | 'ms'
    | 'ms-MY'
    | 'my'
    | 'my-MM'
    | 'nb'
    | 'ne'
    | 'ne-NP'
    | 'nl'
    | 'nl-NL'
    | 'no'
    | 'no-NO'
    | 'pa'
    | 'pa-IN'
    | 'pl'
    | 'pl-PL'
    | 'ps'
    | 'ps-AF'
    | 'pt'
    | 'pt-BR'
    | 'pt-PT'
    | 'ro'
    | 'ro-RO'
    | 'ru'
    | 'ru-RU'
    | 'si'
    | 'si-LK'
    | 'sk'
    | 'sk-SK'
    | 'sl'
    | 'sl-SI'
    | 'sr'
    | 'sr-RS'
    | 'sv'
    | 'sv-SE'
    | 'sw'
    | 'sw-KE'
    | 'ta'
    | 'ta-IN'
    | 'te'
    | 'te-IN'
    | 'th'
    | 'th-TH'
    | 'tr'
    | 'tr-TR'
    | 'uk'
    | 'uk-UA'
    | 'ur'
    | 'ur-PK'
    | 'uz'
    | 'uz-UZ'
    | 'vi'
    | 'vi-VN'
    | 'zh'
    | 'zh-CN'
    | 'zh-Hans'
    | 'zh-Hant'
    | 'zh-HK'
    | 'zh-TW';
  displayLabel: string;
  deeplSourceLanguage?:
    | (
        | 'ar'
        | 'bg'
        | 'cs'
        | 'da'
        | 'de'
        | 'el'
        | 'en'
        | 'es'
        | 'et'
        | 'fi'
        | 'fr'
        | 'he'
        | 'hu'
        | 'id'
        | 'it'
        | 'ja'
        | 'ko'
        | 'lt'
        | 'lv'
        | 'nb'
        | 'nl'
        | 'pl'
        | 'pt'
        | 'ro'
        | 'ru'
        | 'sk'
        | 'sl'
        | 'sv'
        | 'th'
        | 'tr'
        | 'uk'
        | 'vi'
        | 'zh'
      )
    | null;
  deeplTargetLanguage?:
    | (
        | 'ar'
        | 'bg'
        | 'cs'
        | 'da'
        | 'de'
        | 'el'
        | 'en-GB'
        | 'en-US'
        | 'es'
        | 'es-419'
        | 'et'
        | 'fi'
        | 'fr'
        | 'he'
        | 'hu'
        | 'id'
        | 'it'
        | 'ja'
        | 'ko'
        | 'lt'
        | 'lv'
        | 'nb'
        | 'nl'
        | 'pl'
        | 'pt-BR'
        | 'pt-PT'
        | 'ro'
        | 'ru'
        | 'sk'
        | 'sl'
        | 'sv'
        | 'th'
        | 'tr'
        | 'uk'
        | 'vi'
        | 'zh-Hans'
        | 'zh-Hant'
      )
    | null;
  googleMapsLanguage?:
    | (
        | 'af'
        | 'am'
        | 'ar'
        | 'az'
        | 'bg'
        | 'bn'
        | 'cs'
        | 'da'
        | 'de'
        | 'el'
        | 'en'
        | 'en-AU'
        | 'en-GB'
        | 'es'
        | 'es-419'
        | 'et'
        | 'fa'
        | 'fi'
        | 'fr'
        | 'fr-CA'
        | 'gu'
        | 'hi'
        | 'hr'
        | 'hu'
        | 'hy'
        | 'id'
        | 'it'
        | 'ja'
        | 'ka'
        | 'kk'
        | 'km'
        | 'ko'
        | 'lo'
        | 'lt'
        | 'lv'
        | 'ml'
        | 'mn'
        | 'mr'
        | 'ms'
        | 'my'
        | 'ne'
        | 'nl'
        | 'no'
        | 'pa'
        | 'pl'
        | 'pt'
        | 'pt-BR'
        | 'pt-PT'
        | 'ro'
        | 'ru'
        | 'si'
        | 'sk'
        | 'sl'
        | 'sr'
        | 'sv'
        | 'sw'
        | 'ta'
        | 'te'
        | 'th'
        | 'tr'
        | 'uk'
        | 'ur'
        | 'uz'
        | 'vi'
        | 'zh'
        | 'zh-CN'
        | 'zh-HK'
        | 'zh-TW'
      )
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners".
 */
export interface Banner {
  id: string;
  message: string;
  cta?: {
    show?: boolean | null;
    label?: string | null;
    link?: NewLink;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewLink".
 */
export interface NewLink {
  linkType: 'custom' | 'internal';
  doc?: (string | null) | Page;
  queryString?: string | null;
  fragment?: string | null;
  url?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  /**
   * A hero section is the first thing a user sees when they visit a page. Only one hero block can be added to a page. To replace the current hero block by a different block type, remove it and add a new one.
   */
  hero?: (HeroSlides | HeroVideo | HeroHeading)[] | null;
  /**
   * Add blocks to fill the page with content. You can reorder the blocks by dragging and dropping them using the handle on the left side.
   */
  content?:
    | (
        | LeadText
        | ImageWithFloatingText
        | Story
        | Features
        | Separator
        | WideImage
        | TextColumnsWithImages
        | Map
        | Testimonials
        | RoomList
      )[]
    | null;
  seo?: {
    /**
     * The description is shown in search engine results. It should be between 100 and 150 characters.
     */
    description?: string | null;
    /**
     * The image is shown in search engine results and when the page is shared on social media. It will be automatically sized to 1200x630 pixels.
     */
    image?: (string | null) | Media;
  };
  /**
   * Choose the brand to which the page belongs. The page pathname must live within the brand's root path.
   */
  brand: string | Brand;
  /**
   * The pathname is used to navigate to this page. It must be unique and start with the brand's root path.
   */
  pathname: string;
  pathname_locked?: boolean | null;
  pathname_createRedirect?: boolean | null;
  /**
   * The title is shown in the title bar of the browser and in search engine results. Include important keywords for SEO. The brand’s base title is appended to the title.
   */
  title?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroSlides".
 */
export interface HeroSlides {
  /**
   * This heading is only used for SEO purposes and is not shown on the page. Since the slide overlay titles semantically don't define the page's main heading, you can use this field to define the main heading of the page.
   */
  seoPageHeading: string;
  /**
   * You can use this either for a single hero image or a slideshow with multiple images. Each slide can have an overlay title and a call-to-action button. You can add up to six slides.
   */
  slides: {
    image: string | Media;
    /**
     * Depending on the user’s device or window size, the slide often has a different aspect ratio than the image. This setting defines how the image is aligned within the slide area.
     */
    imageAlignment?: ('center' | 'bottom') | null;
    overlayTitle?: {
      show?: boolean | null;
      text?: {
        root: {
          type: string;
          children: {
            type: any;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      } | null;
      supportingText?: {
        root: {
          type: string;
          children: {
            type: any;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      } | null;
      cta?: {
        show?: boolean | null;
        label?: string | null;
        link?: NewLink;
        variant?: ('primary' | 'secondary') | null;
      };
      position?: ('center' | 'top-left' | 'top-right' | 'bottom-right' | 'bottom-left') | null;
      /**
       * The overlay is a semi-transparent black layer that is placed on top of the image to make the text more readable. Choose the intensity that is the best trade-off between readability of the text and brightness of the image.
       */
      overlay?: ('subtle' | 'moderate' | 'intense') | null;
    };
    id?: string | null;
  }[];
  /**
   * Depending on the amount of information in the slides (title, CTA), different intervals might be more suitable. The default value is 7 seconds.
   */
  autoplayIntervalInSeconds?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'HeroSlides';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroVideo".
 */
export interface HeroVideo {
  /**
   * The video should be optimized for web pages before uploading it.
   */
  video: string | Media;
  /**
   * The preview image is shown while the video is still loading. It should be the first frame of the video to provide a seamless transition.
   */
  previewImage?: (string | null) | Media;
  overlayTitle?: {
    show?: boolean | null;
    text?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    supportingText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    cta?: {
      show?: boolean | null;
      label?: string | null;
      link?: NewLink;
      variant?: ('primary' | 'secondary') | null;
    };
    position?: ('center' | 'top-left' | 'top-right' | 'bottom-right' | 'bottom-left') | null;
    /**
     * The overlay is a semi-transparent black layer that is placed on top of the image to make the text more readable. Choose the intensity that is the best trade-off between readability of the text and brightness of the image.
     */
    overlay?: ('subtle' | 'moderate' | 'intense') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'HeroVideo';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroHeading".
 */
export interface HeroHeading {
  heading: string;
  image?: (string | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'HeroHeading';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LeadText".
 */
export interface LeadText {
  heading?: string | null;
  text: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  cta?: {
    show?: boolean | null;
    label?: string | null;
    link?: NewLink;
    variant?: ('primary' | 'secondary') | null;
  };
  elementId?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'LeadText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageWithFloatingText".
 */
export interface ImageWithFloatingText {
  image: string | Media;
  overlayTitle: {
    text: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    position?: ('top-left' | 'top-right') | null;
    /**
     * The overlay is a semi-transparent black layer that is placed on top of the image to make the text more readable. Choose the intensity that is the best trade-off between readability of the text and brightness of the image.
     */
    overlay?: ('subtle' | 'moderate' | 'intense') | null;
  };
  text: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  elementId?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ImageWithFloatingText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Story".
 */
export interface Story {
  heading?: string | null;
  text: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  image?: (string | null) | Media;
  imagePosition?: ('left' | 'right') | null;
  /**
   * Check this box to display the image in grayscale.
   */
  grayscaleImage?: boolean | null;
  elementId?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'Story';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Features".
 */
export interface Features {
  orientation?: ('first-image-left' | 'first-image-right') | null;
  items: {
    image: string | Media;
    heading: string;
    text: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    cta?: {
      show?: boolean | null;
      label?: string | null;
      link?: NewLink;
      variant?: ('primary' | 'secondary') | null;
    };
    id?: string | null;
  }[];
  elementId?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'Features';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Separator".
 */
export interface Separator {
  id?: string | null;
  blockName?: string | null;
  blockType: 'Separator';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WideImage".
 */
export interface WideImage {
  image: string | Media;
  overlayTextBox?: {
    show?: boolean | null;
    heading?: string | null;
    text?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    cta?: {
      show?: boolean | null;
      label?: string | null;
      link?: NewLink;
      variant?: ('primary' | 'secondary') | null;
    };
    position?: ('top-left' | 'top-right' | 'bottom-left' | 'bottom-right') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'WideImage';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextColumnsWithImages".
 */
export interface TextColumnsWithImages {
  heading?: string | null;
  text?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Note that the specified number of columns per row is for standard desktop screens (width of 1280px or more) and will be reduced automatically on smaller screens.
   */
  numberOfColumns?: number | null;
  items: {
    image?: (string | null) | Media;
    size?: ('full' | 'medium' | 'small') | null;
    heading?: string | null;
    text?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    cta?: {
      show?: boolean | null;
      label?: string | null;
      link?: NewLink;
      variant?: ('primary' | 'secondary') | null;
    };
    id?: string | null;
  }[];
  elementId?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'TextColumnsWithImages';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Map".
 */
export interface Map {
  /**
   * Enter the address to display on the map, including the business name. It should resolve unambiguously to a place on Google Maps.
   */
  address: string;
  /**
   * Enter a number from 0 to 22. The level of detail for the different zoom levels is approximately: 1—World, 5—Landmass/continent, 10—City, 15—Streets, 20—Buildings. Floating point numbers are allowed, e.g. 14.5.
   */
  zoomLevel: number;
  overlayTextBox: {
    heading: string;
    text: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    callToActionLabel?: string | null;
    position?: ('top-left' | 'top-right' | 'bottom-left' | 'bottom-right') | null;
  };
  elementId?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'Map';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Testimonials".
 */
export interface Testimonials {
  heading?: string | null;
  supportingText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  items?:
    | {
        text: string;
        author: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RoomList".
 */
export interface RoomList {
  rooms: {
    heading: string;
    text?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    images: {
      image: string | Media;
      caption?: string | null;
      id?: string | null;
    }[];
    cta: {
      label: string;
      link: NewLink;
      variant?: ('primary' | 'secondary') | null;
    };
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'RoomList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: string;
  name: string;
  homeLink?: NewLink;
  /**
   * The localized root path for this brand. Pages for this brand must use this path or a child path below it.
   */
  rootPath: string;
  /**
   * Choose the theme color used by the frontend for this brand.
   */
  themeColor: 'default' | 'aqua' | 'azul';
  /**
   * The base title is appended to the titles of the brand’s pages. If the page does not have a title, the base title will be used as the title. Include important keywords in the title for SEO.
   */
  baseTitle?: string | null;
  logo: string | Media;
  /**
   * A banner is useful to announce promotions or important news and can have a call to action. It will be shown on all pages of the brand.
   */
  banner?: (string | null) | Banner;
  navLinks?:
    | {
        label: string;
        link: NewLink;
        id?: string | null;
      }[]
    | null;
  bookCta?: {
    show?: boolean | null;
    label?: string | null;
    link?: NewLink;
  };
  footer?: {
    linkGroups?:
      | {
          title: string;
          links?:
            | {
                label: string;
                link: NewLink;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  fromPathname: string;
  to: {
    page: string | Page;
    queryString?: string | null;
    fragment?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'api-keys';
        value: string | ApiKey;
      } | null)
    | ({
        relationTo: 'locale-configs';
        value: string | LocaleConfig;
      } | null)
    | ({
        relationTo: 'banners';
        value: string | Banner;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'brands';
        value: string | Brand;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: string | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'api-keys';
        value: string | ApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'api-keys';
        value: string | ApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  comment?: T;
  alt?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys_select".
 */
export interface ApiKeysSelect<T extends boolean = true> {
  role?: T;
  remark?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locale-configs_select".
 */
export interface LocaleConfigsSelect<T extends boolean = true> {
  id?: T;
  locale?: T;
  displayLabel?: T;
  deeplSourceLanguage?: T;
  deeplTargetLanguage?: T;
  googleMapsLanguage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners_select".
 */
export interface BannersSelect<T extends boolean = true> {
  message?: T;
  cta?:
    | T
    | {
        show?: T;
        label?: T;
        link?: T | NewLinkSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewLink_select".
 */
export interface NewLinkSelect<T extends boolean = true> {
  linkType?: T;
  doc?: T;
  queryString?: T;
  fragment?: T;
  url?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        HeroSlides?: T | HeroSlidesSelect<T>;
        HeroVideo?: T | HeroVideoSelect<T>;
        HeroHeading?: T | HeroHeadingSelect<T>;
      };
  content?:
    | T
    | {
        LeadText?: T | LeadTextSelect<T>;
        ImageWithFloatingText?: T | ImageWithFloatingTextSelect<T>;
        Story?: T | StorySelect<T>;
        Features?: T | FeaturesSelect<T>;
        Separator?: T | SeparatorSelect<T>;
        WideImage?: T | WideImageSelect<T>;
        TextColumnsWithImages?: T | TextColumnsWithImagesSelect<T>;
        Map?: T | MapSelect<T>;
        testimonials?: T | TestimonialsSelect<T>;
        RoomList?: T | RoomListSelect<T>;
      };
  seo?:
    | T
    | {
        description?: T;
        image?: T;
      };
  brand?: T;
  pathname?: T;
  pathname_locked?: T;
  pathname_createRedirect?: T;
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroSlides_select".
 */
export interface HeroSlidesSelect<T extends boolean = true> {
  seoPageHeading?: T;
  slides?:
    | T
    | {
        image?: T;
        imageAlignment?: T;
        overlayTitle?:
          | T
          | {
              show?: T;
              text?: T;
              supportingText?: T;
              cta?:
                | T
                | {
                    show?: T;
                    label?: T;
                    link?: T | NewLinkSelect<T>;
                    variant?: T;
                  };
              position?: T;
              overlay?: T;
            };
        id?: T;
      };
  autoplayIntervalInSeconds?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroVideo_select".
 */
export interface HeroVideoSelect<T extends boolean = true> {
  video?: T;
  previewImage?: T;
  overlayTitle?:
    | T
    | {
        show?: T;
        text?: T;
        supportingText?: T;
        cta?:
          | T
          | {
              show?: T;
              label?: T;
              link?: T | NewLinkSelect<T>;
              variant?: T;
            };
        position?: T;
        overlay?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroHeading_select".
 */
export interface HeroHeadingSelect<T extends boolean = true> {
  heading?: T;
  image?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LeadText_select".
 */
export interface LeadTextSelect<T extends boolean = true> {
  heading?: T;
  text?: T;
  cta?:
    | T
    | {
        show?: T;
        label?: T;
        link?: T | NewLinkSelect<T>;
        variant?: T;
      };
  elementId?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageWithFloatingText_select".
 */
export interface ImageWithFloatingTextSelect<T extends boolean = true> {
  image?: T;
  overlayTitle?:
    | T
    | {
        text?: T;
        position?: T;
        overlay?: T;
      };
  text?: T;
  elementId?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Story_select".
 */
export interface StorySelect<T extends boolean = true> {
  heading?: T;
  text?: T;
  image?: T;
  imagePosition?: T;
  grayscaleImage?: T;
  elementId?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Features_select".
 */
export interface FeaturesSelect<T extends boolean = true> {
  orientation?: T;
  items?:
    | T
    | {
        image?: T;
        heading?: T;
        text?: T;
        cta?:
          | T
          | {
              show?: T;
              label?: T;
              link?: T | NewLinkSelect<T>;
              variant?: T;
            };
        id?: T;
      };
  elementId?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Separator_select".
 */
export interface SeparatorSelect<T extends boolean = true> {
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WideImage_select".
 */
export interface WideImageSelect<T extends boolean = true> {
  image?: T;
  overlayTextBox?:
    | T
    | {
        show?: T;
        heading?: T;
        text?: T;
        cta?:
          | T
          | {
              show?: T;
              label?: T;
              link?: T | NewLinkSelect<T>;
              variant?: T;
            };
        position?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextColumnsWithImages_select".
 */
export interface TextColumnsWithImagesSelect<T extends boolean = true> {
  heading?: T;
  text?: T;
  numberOfColumns?: T;
  items?:
    | T
    | {
        image?: T;
        size?: T;
        heading?: T;
        text?: T;
        cta?:
          | T
          | {
              show?: T;
              label?: T;
              link?: T | NewLinkSelect<T>;
              variant?: T;
            };
        id?: T;
      };
  elementId?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Map_select".
 */
export interface MapSelect<T extends boolean = true> {
  address?: T;
  zoomLevel?: T;
  overlayTextBox?:
    | T
    | {
        heading?: T;
        text?: T;
        callToActionLabel?: T;
        position?: T;
      };
  elementId?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  heading?: T;
  supportingText?: T;
  items?:
    | T
    | {
        text?: T;
        author?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RoomList_select".
 */
export interface RoomListSelect<T extends boolean = true> {
  rooms?:
    | T
    | {
        heading?: T;
        text?: T;
        images?:
          | T
          | {
              image?: T;
              caption?: T;
              id?: T;
            };
        cta?:
          | T
          | {
              label?: T;
              link?: T | NewLinkSelect<T>;
              variant?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  fromPathname?: T;
  to?:
    | T
    | {
        page?: T;
        queryString?: T;
        fragment?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  homeLink?: T | NewLinkSelect<T>;
  rootPath?: T;
  themeColor?: T;
  baseTitle?: T;
  logo?: T;
  banner?: T;
  navLinks?:
    | T
    | {
        label?: T;
        link?: T | NewLinkSelect<T>;
        id?: T;
      };
  bookCta?:
    | T
    | {
        show?: T;
        label?: T;
        link?: T | NewLinkSelect<T>;
      };
  footer?:
    | T
    | {
        linkGroups?:
          | T
          | {
              title?: T;
              links?:
                | T
                | {
                    label?: T;
                    link?: T | NewLinkSelect<T>;
                    id?: T;
                  };
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Settings {
  id: string;
  publishedLocales: {
    /**
     * Select locales with completely translated content to make them available to the user on the website. To add a new locale, it must be first added to the 'Locale Configurations' collection.
     */
    publishedLocales: (string | LocaleConfig)[];
    /**
     * The fallback locale is used when a translation is not available in the requested locale. It must be one of the published locales.
     */
    fallbackLocale: string | LocaleConfig;
  };
  /**
   * Hide the complete website and show a maintenance screen instead.
   */
  maintenanceScreen?: {
    show?: boolean | null;
    message?: string | null;
  };
  maps?: {
    /**
     * Enter the region code for maps, e.g. CO for Colombia. Must be two letters in uppercase. See https://developers.google.com/maps/coverage#coverage-legend
     */
    region?: string | null;
    /**
     * Enter the ID of the map to display. This is the ID of the map in the Google Maps Platform and defines styling and POI settings.
     */
    mapId?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "common".
 */
export interface Common {
  id: string;
  pageNotFoundScreen?: {
    heading?: string | null;
    text?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  errorScreen?: {
    heading?: string | null;
    text?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  uiLabels: {
    banner?: {
      dismiss?: string | null;
    };
    slidesBlock?: {
      /**
       * Use the {{slide}} placeholder to display the slide number.
       */
      goToSlide?: string | null;
    };
    errorBoundary?: {
      title?: string | null;
      text?: string | null;
    };
    maintenanceScreen?: {
      login?: string | null;
    };
    login?: {
      email?: string | null;
      password?: string | null;
      submit?: string | null;
    };
    test: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  publishedLocales?:
    | T
    | {
        publishedLocales?: T;
        fallbackLocale?: T;
      };
  maintenanceScreen?:
    | T
    | {
        show?: T;
        message?: T;
      };
  maps?:
    | T
    | {
        region?: T;
        mapId?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "common_select".
 */
export interface CommonSelect<T extends boolean = true> {
  pageNotFoundScreen?:
    | T
    | {
        heading?: T;
        text?: T;
      };
  errorScreen?:
    | T
    | {
        heading?: T;
        text?: T;
      };
  uiLabels?:
    | T
    | {
        banner?:
          | T
          | {
              dismiss?: T;
            };
        slidesBlock?:
          | T
          | {
              goToSlide?: T;
            };
        errorBoundary?:
          | T
          | {
              title?: T;
              text?: T;
            };
        maintenanceScreen?:
          | T
          | {
              login?: T;
            };
        login?:
          | T
          | {
              email?: T;
              password?: T;
              submit?: T;
            };
        test?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}